# Generated by Django 6.0.3 on 2026-03-20 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolrequest',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carpoolrequest',
            name='pickup_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pickups', to='network.node'),
        ),
        migrations.AddField(
            model_name='trip',
            name='current_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='current_trips_here', to='network.node'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_driven', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trips_ending_here', to='network.node'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trips_starting_here', to='network.node'),
        ),
        migrations.AddField(
            model_name='carpoolrequest',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='trips.trip'),
        ),
    ]
