# Generated by Django 6.0.3 on 2026-03-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_carpoolrequest_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='max_passangers',
            new_name='max_passengers',
        ),
    ]
